<?php

// $Id: review360_base.info,v 1.4 2011/07/04 13:25:57 dries Exp $
/**
 * Implementation of hook_init
 */
function review360_base_init() {
    
}

function review360_base_js_alter(&$javascript) {
    
}

/**
 * Implements hook_help().
 */
function review360_base_help($path, $arg) {
    switch ($path) {
        case 'admin/help#review360_base':
            $output = '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Review 360 基础模块');
            return $output;
    }
}

/**
 * Implements hook_permission().
 */
function review360_base_permission() {
    return array(
        'review360_base' => array(
            'title' => t('Review360 Base'),
        ),

        'review360_base_interviewer' => array(
            'title' => t('Review360 Interviewer'),
        ),
        
    );
}

function review360_base_menu() {
    $items = array();
    $items['dashboard'] = array(
        'title' => t('Dashboard'),
        'page callback'     => 'review360_base_dashboard_call_back',
        'access arguments'  => array('review360_base'),
        'weight'            => -47,
    );
    // USER ===============================
    $items['usermanagement'] = array(
        'title' => t('用户管理'),
        'page callback'     => 'review360_usermanage_call_back',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_user_management.inc',
        'weight'            => -47,
    );
    
    $items['usermanagement/add'] = array(
        'title' => t('用户管理'),
        'page callback'     => 'save_new_user_group_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_user_management.inc',
        'weight'            => -47,
    );
    
    $items['usermanagement/grouplist'] = array(
        'title' => t('用户管理'),
        'page callback'     => 'get_user_group_list_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_user_management.inc',
        'weight'            => -47,
    );
    
    $items['usermanagement/group/edit/%'] = array(
        'title' => t('用户修改'),
        'page callback'     => 'review360_group_edit',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_user_management.inc',
        'page arguments' => array(3),
        'weight'            => -47,
    );
    
     $items['usermanagement/group/changename'] = array(
        'title' => t('用户修改'),
        'page callback'     => 'review360_group_change_name_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_user_management.inc',
        'weight'            => -47,
    );
    
    $items['usermanagement/group/del'] = array(
        'title' => t('删除用户'),
        'page callback'     => 'review360_group_del_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_user_management.inc',
        'weight'            => -47,
    );
    
    $items['usermanagement/upload/%'] = array(
        'title' => t('导入用户'),
        'page callback'     => 'review360_user_upload',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_user_management.inc',
        'page arguments' => array(2),
        'weight'            => -47,
    );
     
    $items['export_user_file/%'] = array(
        'title' => t('导出用户'),
        'page callback'     => 'export_user_file',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_user_management.inc',
        'page arguments' => array(1),
        'weight'            => -47,
    );
    // SURVEY ===============================
    $items['surveymanagement'] = array(
        'title' => t('题库管理'),
        'page callback'     => 'review360_survey_management_view',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_survey_management.inc',
        'weight'            => -47,
    );
    
    $items['surveymanagement/add'] = array(
        'title' => t('新增问卷'),
        'page callback'     => 'save_new_survey_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_survey_management.inc',
        'weight'            => -47,
    );
    
    $items['surveymanagement/surveylist'] = array(
        'title' => t('问卷管理'),
        'page callback'     => 'get_survey_list_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_survey_management.inc',
        'weight'            => -47,
    );
    
    $items['surveymanagement/edit/%'] = array(
        'title' => t('问卷修改'),
        'page callback'     => 'review360_survey_edit',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_survey_management.inc',
        'page arguments' => array(2),
        'weight'            => -47,
    );
    
    $items['surveymanagement/del'] = array(
        'title' => t('删除用户'),
        'page callback'     => 'review360_survey_del_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_survey_management.inc',
        'weight'            => -47,
    );
     
    $items['surveymanagement/export/%'] = array(
        'title' => t('问卷修改'),
        'page callback'     => 'review360_survey_export',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_survey_management.inc',
        'page arguments' => array(2),
        'weight'            => -47,
    );
    
    $items['surveymanagement/report_export/%'] = array(
        'title' => t('问卷修改'),
        'page callback'     => 'review360_survey_report_export',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_survey_management.inc',
        'page arguments' => array(2),
        'weight'            => -47,
    );
     
    $items['surveymanagement/init'] = array(
        'title' => t('初始化评分标准'),
        'page callback'     => 'review360_surveymanagement_init_call_back',
        'file'              => 'inc/admin/review360_survey_management_init.inc',
        'access arguments'  => array('review360_base'),
        'weight'            => -47,
    );
    
     $items['surveymanagement/generatereport'] = array(
        'title' => t('初始化评分标准'),
        'page callback'     => 'generate_survey_result',
//        'file'              => 'inc/admin/review360_survey_management_init.inc',
        'access arguments'  => array('review360_base'),
        'weight'            => -47,
    );
    
    
    // EXAM ===============================
    $items['exammanagement'] = array(
        'title' => t('问卷管理'),
        'page callback'     => 'review360_exam_management_view',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_exam_management.inc',
        'weight'            => -47,
    );
   
    $items['exammanagement/add'] = array(
        'title' => t('新增问卷'),
        'page callback'     => 'save_new_exam_group_ajax',
        'access arguments'  => array('review360_exam_manage'),
        'file'              => 'inc/admin/review360_exam_management.inc',
        'weight'            => -47,
    );
    
    $items['exammanagement/examlist'] = array(
        'title' => t('问卷管理'),
        'page callback'     => 'get_exam_list_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_exam_management.inc',
        'weight'            => -47,
    );
    
    $items['exammanagement/edit/%'] = array(
        'title' => t('问卷修改'),
        'page callback'     => 'review360_exam_edit',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_exam_management.inc',
        'page arguments' => array(2),
        'weight'            => -47,
    );
    
     $items['exammanagement/changename'] = array(
        'title' => t('问卷修改'),
        'page callback'     => 'review360_group_change_name_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_exam_management.inc',
        'weight'            => -47,
    );
    
    $items['exammanagement/del'] = array(
        'title' => t('问卷删除'),
        'page callback'     => 'review360_exam_del_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_exam_management.inc',
        'weight'            => -47,
    );
    
    $items['exammanagement/upload/%'] = array(
        'title' => t('导入问卷'),
        'page callback'     => 'review360_exam_upload',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_exam_management.inc',
        'page arguments' => array(2),
        'weight'            => -47,
    );
     
    $items['export_exam_file/%'] = array(
        'title' => t('导出问卷'),
        'page callback'     => 'export_exam_file',
        'access arguments'  => array('review360_base`'),
        'file'              => 'inc/admin/review360_exam_management.inc',
        'page arguments' => array(1),
        'weight'            => -47,
    );
    // ===================== user filter===================
    $items['candidate/filter'] = array(
        'title' => t('用户筛选'),
        'page callback'     => 'review360_candidate_filter_view',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_candidate_filter.inc',
        'weight'            => -47,
    );
    
    $items['candidate/filter/surveyrst'] = array(
        'title' => t('用户筛选'),
        'page callback'     => 'get_survey_rst_ajax',
        'access arguments'  => array('review360_base'),
        'file'              => 'inc/admin/review360_candidate_filter.inc',
        'weight'            => -47,
    );
    
    //================== member===================
    $items['interviewer/onboard'] = array(
        'title' => t('受访者登陆'),
        'page callback'     => 'review360_interviewer_onboard',
        'access arguments'  => array('review360_base_interviewer'),
        'file'              => 'inc/member/review360_interviewer.inc',
        'weight'            => -47,
    );
    
    $items['interviewer/infor/%'] = array(
        'title' => t('受访者信息管理'),
        'page callback'     => 'review360_interviewer_infor',
        'access arguments'  => array('review360_base_interviewer'),
        'file'              => 'inc/member/review360_interviewer.inc',
        'page arguments' => array(2),
        'weight'            => -47,
    );
    
     $items['interviewer/exam/%'] = array(
        'title' => t('受访者登陆'),
        'page callback'     => 'review360_interviewer_exam',
        'access arguments'  => array('review360_base_interviewer'),
        'file'              => 'inc/member/review360_interviewer_exam.inc',
        'page arguments' => array(2),
        'weight'            => -47,
    );
     
    $items['interviewer/survey/%/%'] = array(
        'title' => t('受访者信息管理'),
        'page callback'     => 'review360_interviewer_survey',
        'access arguments'  => array('review360_base_interviewer'),
        'file'              => 'inc/member/review360_interviewer_survey.inc',
        'page arguments' => array(2,3),
        'weight'            => -47,
    );
    
     $items['interviewer/survey/submitted/%'] = array(
        'title' => t('受访者信息管理'),
        'page callback'     => 'review360_interviewer_survey_submit',
        'access arguments'  => array('review360_base_interviewer'),
        'file'              => 'inc/member/review360_interviewer_survey.inc',
        'page arguments' => array(3),
        'weight'            => -47,
    );

    return $items;
}

function review360_base_dashboard_call_back() {
    $pageContent = '<h2>欢迎使用本系统！</h2>';
    return $pageContent;
}

function review360_base_block_info() {
    $blocks['left_menu'] = array(
        'info' => t('Left Menu'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}

function review360_base_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'left_menu':
            $output = theme('left_menu');
            $block['content'] = $output;
            break;
    }
    return $block;
}

function review360_base_theme() {
    return array(
        'left_menu' => array(
            'template' => 'template/review360_base_left_menu',
        ),
         'right_content' => array(
            'template' => 'template/review360_base_right_content',
            'variables' => array('page_content' => NULL,'is_html'=>false),
        ),
        // ===================== admin====================================
        'review360_base_config' => array(
            'template' => 'template/admin/review360_base_config',
        ),
        'review360_group_edit' => array(
            'template' => 'template/admin/review360_group_edit',
            'variables' => array('group_id' => NULL),
        ),
         'review360_survey_view' => array(
            'template' => 'template/admin/review360_survey_view',
        ),
        
        'review360_exam_mg_view' => array(
            'template' => 'template/admin/review360_exam_mg_view',
        ),
        'review360_exam_mg_edit' => array(
            'template' => 'template/admin/review360_exam_mg_edit',
            'variables' => array('exam_id' => NULL),
        ),
        'review360_survey_edit' => array(
            'template' => 'template/admin/review360_survey_mg_edit',
            'variables' => array('survey_id' => NULL),
        ),
        //===================== user filter================
        //review360_candidate_filter_view
        'review360_candidate_filter_view' => array(
            'template' => 'template/admin/review360_candidate_filter_view',
         //   'variables' => array('survey_id' => NULL),
        ),
        // ===================== member====================================
        'review360_interviewer_onboard_view' => array(
            'template' => 'template/member/review360_interviewer_onboard_view',
//            'variables' => array('survey_id' => NULL),
        ),
         'review360_interviewer_infor_view' => array(
            'template' => 'template/member/review360_interviewer_infor_view',
            'variables' => array('user_key' => NULL),
        ),
        'review360_interviewer_exam_view' => array(
            'template' => 'template/member/review360_interviewer_exam_choose',
            'variables' => array('user_key' => NULL),
        ),
        
        'review360_interviewer_survey_view' => array(
            'template' => 'template/member/review360_interviewer_survey_view',
            'variables' => array('user_key' => NULL,'nid' => NULL),
        ),
        'review360_interviewer_survey_submitted' => array(
            'template' => 'template/member/review360_interviewer_survey_submitted',
            'variables' => array('user_key' => NULL),
        ),
        'review360_interviewer_school' => array(
            'template' => 'template/member/review360_interviewer_school_view',
//            'variables' => array('user_key' => NULL),
        ),
        
    );
}


function rend_block_by_name($model_name, $block_name) {
    $block = block_load($model_name, $block_name);
    $block_array = array($block);
    $render_block = _block_render_blocks($block_array);
    $render_block_array = _block_get_renderable_array($render_block);
    return drupal_render($render_block_array);
}

function rend_left_menu_li($get_q,$text,$path){
    if(0 === strpos($get_q,$path)){
        return ' <li role="presentation" class="active" >'. l($text,$path).'</li>';
    } else {
         return ' <li role="presentation">'. l($text,$path).'</li>';
    }
}

function review360_base_export_file($fileName,$objPHPExcel){
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="'.$fileName.'"');
    header('Cache-Control: max-age=0');
    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
    $objWriter->save('php://output');
}

function review360_base_export_zip_file($file_name,$get_url){
    header("Content-Type: application/force-download");
    header("Content-Transfer-Encoding: binary");
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename='.$file_name);
    header("Connection: close");
    readfile($get_url);
    return true;
}

function random_string($length = 8) {
    $str = '';
    for ($i = 0; $i < $length; $i++) {
        $str .= chr(mt_rand(65, 90));
        $str .= chr(mt_rand(97, 122));
    }
    return $str;
}

function prepare_timestamp_to_str($timestamp){
    if(!$timestamp) $timestamp = time();
    return date('Y-m-d', $timestamp).'';
}

function prepare_date_to_timestamp($date_str){
    return strtotime($date_str);
}

function prepare_form_stdClass($args){
    $std = new stdClass();
    if ($args && $args['build_info'] && $args['build_info']['args'])
        $std = $args['build_info']['args'][0];
    return $std;
}

function prepare_default_value($val){
    if(isset($val)) return $val;
    return '';
}

function get_exam_by_key($key){
    $query = "select exam_nid  from review360_survey_user_exam
            where user_key = '$key'";
    $result = db_query($query)->fetchAll();
    return $result;
}

function get_user_exam_by_nid($nid){
    $query = "select exam_nid nid,nick_name  from review360_survey_user_exam
            where exam_nid = '$nid'";
    $result = db_query($query)->fetchObject();
    return $result;
}

function get_user_exam_by_key($key){
    $query = "select exam_nid nid,nick_name  from review360_survey_user_exam
            where user_key = '$key'";
    $result = db_query($query)->fetchAll();
    return $result;
}

function get_user_infor_by_key($key){
    $query = "select *  from review360_survey_user
            where survey_user_key = '$key'";
    $result = db_query($query)->fetchObject();
    return $result;
}

function get_survey_by_id($survey_id){
    $query = "select * from  review360_survey where survey_id = $survey_id";
    $result = db_query($query)->fetchObject();
    return $result;
}


function array_to_object($array) {  
    if (is_array($array)) {  
        $obj = new StdClass();  
   
        foreach ($array as $key => $val){  
            $obj->$key = $val;  
        }  
    }  
    else { $obj = $array; }  
   
    return $obj;  
}  
function object_to_array($object) {  
    if (is_object($object)) {  
        foreach ($object as $key => $value) {  
            $array[$key] = $value;  
        }  
    }  
    else {  
        $array = $object;  
    }  
    return $array;  
}  


function engaged_array(){
    return array(
            0 => '-- 请选择 --',
            'IT/软硬件服务/电子商务/因特网运营' => 'IT/软硬件服务/电子商务/因特网运营',
            '快速消费品(食品/饮料/化妆品)' => '快速消费品(食品/饮料/化妆品)',
            '批发/零售' => '批发/零售',
            '服装/纺织/皮革' => '服装/纺织/皮革',
            '家具/工艺品/玩具' => '家具/工艺品/玩具',
            '教育/培训/科研/院校' => '教育/培训/科研/院校',
            '家电' => '家电',
            '通信/电信运营/网络设备/增值服务' => '通信/电信运营/网络设备/增值服务',
            '制造业 ' => '制造业',
            '汽车及零配件' => '汽车及零配件',
            '餐饮/娱乐/旅游/酒店/生活服务' => '餐饮/娱乐/旅游/酒店/生活服务',
            '办公用品及设备' => '办公用品及设备',
            '会计/审计' => '会计/审计',
            '法律' => '法律',
            '银行/保险/证券/投资银行/风险基金' => '银行/保险/证券/投资银行/风险基金',
            '电子技术/半导体/集成电路' => '电子技术/半导体/集成电路',
            '仪器仪表/工业自动化' => '仪器仪表/工业自动化',
            '贸易/进出口' => '贸易/进出口',
            '机械/设备/重工' => '机械/设备/重工',
            '制药/生物工程/医疗设备/器械' => '制药/生物工程/医疗设备/器械',
            '医疗/护理/保健/卫生' => '医疗/护理/保健/卫生',
            '广告/公关/媒体/艺术' => '广告/公关/媒体/艺术',
            '出版/印刷/包装' => '出版/印刷/包装',
            '房地产开发/建筑工程/装潢/设计' => '房地产开发/建筑工程/装潢/设计',
            '物业管理/商业中心' => '物业管理/商业中心',
            '中介/咨询/猎头/认证' => '中介/咨询/猎头/认证',
            '交通/运输/物流' => '交通/运输/物流',
            '航天/航空/能源/化工' => '航天/航空/能源/化工',
            '农业/渔业/林业' => '农业/渔业/林业',
            '其他行业' => '其他行业',
        );
}

function experience_array(){
    return array(
            0=>'-- 请选择 --',
            1=>'1年以下',
            2=>'1~2年',
            3=>'2~3年',
            4=>'3~5年',
            5=>'5~10年',
            6=>'10~20年',
            7=>'20年以上',
        );
}

function specialty_array(){
    return array(
            0 => '-- 请选择 --',
            '哲学' => '哲学',
            '经济学' => '经济学',
            '法学' => '法学',
            '教育学' => '教育学',
            '文学' => '文学',
            '历史学' => '历史学',
            '理学' => '理学',
            '工学' => '工学',
            '农学' => '农学',
            '医学' => '医学',
            '哲学' => '军事学',
            '管理学' => '管理学',
        );
}

function bachelor_array(){
    return array(
            0=>'-- 请选择 --',
            1=>'高中以下',
            2=>'中专或高中',
            3=>'大专',
            4=>'大学本科',
            5=>'硕士研究生',
            6=>'博士研究生及以上',
        );
}


function generate_survey_result(){
    $query = "select *  from review360_survey_user_exam rsue "
            . "where is_submited = 1 and is_generate_result = 0 and is_generate_report = 0";
    $exams = db_query($query)->fetchAll();
    foreach($exams as  $exam){
        generate_survey_result_by_sv($exam);
    }
}

function generate_survey_result_by_sv($exam){
    $result = get_survey_rst_by_nid($exam->exam_nid);
    insert_user_survey_result($result->in_working_me,$exam->s_id,$exam->se_id,$exam->exam_nid,"in_working_me");
    insert_user_survey_result($result->innate,$exam->s_id,$exam->se_id,$exam->exam_nid,"innate");
    insert_user_survey_result($result->other,$exam->s_id,$exam->se_id,$exam->exam_nid,"other");
    insert_user_survey_result($result->stress,$exam->s_id,$exam->se_id,$exam->exam_nid,"stress");

    update_status_of_generate_report($exam->exam_nid);
}

function insert_user_survey_result($rst,$sid,$survey_exam_id,$nid,$quadrant){
    $field_array = array();
    $field_array['sid'] = $sid;
    $field_array['se_id'] = $survey_exam_id;
    $field_array['nid'] = $nid;
    $field_array['quadrant'] = $quadrant;
    $field_array['d'] = $rst->d;
    $field_array['i'] = $rst->i;
    $field_array['s'] = $rst->s;
    $field_array['c'] = $rst->c;
    $field_array['update_date'] = time();
    $field_array['create_date'] = time();
    $rst = db_insert('review360_survey_exam_result')->fields($field_array)->execute();
}

//function is_submit($nid,$su_id){
//    $query = "select count(nid) num from webform_submissions where nid = $nid";
//    $result = db_query($query)->fetchObject();
//    if($result->num >0) {
//        db_update('review360_survey_user')
//         ->fields(array(
//               'is_submit' => 1,
//               'update_date' => time(),
//           ))
//         ->condition('su_id', $su_id)
//         ->execute();
//        return 1;
//    }
//    return 0;
//}

function update_status_of_generate_report($nid){
   return db_update('review360_survey_user_exam')
         ->fields(array(
               'is_generate_result' => 1,
               'update_date' => time(),
           ))
         ->condition('exam_nid', $nid)
         ->execute();
}

function get_survey_rst_by_nid($nid){
    $dis_like_str  = '最不符合';
    $like_str= '最符合';
//    $nid = create_new_webform_node($survey_name);
    $query = "select wc.name,wsd.cid,wsd.data from webform_component wc
        inner join webform_submitted_data
        wsd on wc.nid = wsd.nid and wc.cid = wsd.cid
        where wc.nid = $nid
        and (wc.name = '$dis_like_str' or wc.name = '$like_str')
        group by wc.name,wsd.cid";

    $query_rst = db_query($query)->fetchAll();
    $like = prepare_rst_std('like');
    $dis_like = prepare_rst_std('dis_like');
    foreach($query_rst as $item){
        if($item->name == $dis_like_str){
            sum_rst_data($item,$dis_like);
        } else if($item->name == $like_str){
            sum_rst_data($item,$like);
        }
    }
   
    return generate_survey_rst($like,$dis_like);
}

function prepare_rst_std($type){
    $std = new stdClass();
    $std->type = $type;
    $std->d =0;
    $std->i =0;
    $std->s =0;
    $std->c =0;
    return $std;
}

function sum_rst_data($item,&$std){
   switch($item->data){
       case 'D': $std->d++; return $std;
       case 'I': $std->i++; return $std;
       case 'S': $std->s++; return $std;
       case 'C': $std->c++; return $std;
   }
   return $std;
}

function prepare_result($like,$dis_like,$type){
    switch($type){
       case 'd': return prepare_result_parm($like->d,$dis_like->d);
       case 'i': return prepare_result_parm($like->i,$dis_like->i);
       case 's': return prepare_result_parm($like->s,$dis_like->s);
       case 'c': return prepare_result_parm($like->c,$dis_like->c);
    }
}

function prepare_result_parm($like,$dis_like){
    $std = new stdClass();
    $std->in_working_me = $like;
    $std->innate = 6 - $dis_like;
    $std->other = $std->in_working_me + $std->innate;
    $std->stress = $std->in_working_me - $std->innate;
    return $std;
}

function generate_survey_rst($like,$dis_like){
    $d = prepare_result($like,$dis_like,'d');
    $i = prepare_result($like,$dis_like,'i');
    $s = prepare_result($like,$dis_like,'s');
    $c = prepare_result($like,$dis_like,'c');
    
    $rst = new stdClass();
    $rst->in_working_me = new stdClass();
    $rst->in_working_me->d = $d->in_working_me;
    $rst->in_working_me->i = $i->in_working_me;
    $rst->in_working_me->s = $s->in_working_me;
    $rst->in_working_me->c = $c->in_working_me;
    
    $rst->innate = new stdClass();
    $rst->innate->d = $d->innate;
    $rst->innate->i = $i->innate;
    $rst->innate->s = $s->innate;
    $rst->innate->c = $c->innate;
    
    $rst->other = new stdClass();
    $rst->other->d = $d->other;
    $rst->other->i = $i->other;
    $rst->other->s = $s->other;
    $rst->other->c = $c->other;
    
    $rst->stress = new stdClass();
    $rst->stress->d = $d->stress;
    $rst->stress->i = $i->stress;
    $rst->stress->s = $s->stress;
    $rst->stress->c = $c->stress;
    
    return $rst;
}

 function is_submited($nid){
    $query = "select count(sid)>0 from webform_submissions
        where nid = $nid and is_draft =0 ";
    $result = db_query($query)->fetchField();
    return $result;
}
    
function update_user_exam_status($nid){
    return db_update('review360_survey_user_exam')
         ->fields(array(
               'is_submited' => 1,
               'update_date' => time(),
           ))
         ->condition('exam_nid', $nid)
         ->condition('is_submited', 0)
         ->execute();
}